'use strict';
/* Meeting Q&A answers for the AI impostors, generated by Gemini.
 * game.aiProvider = createAnswerProvider(...)  ->  provider.answer(ctx) -> Promise<{ text, llmMs, source } | null>
 * Null / rejection means "use the built-in local answer" (core handles it), so a turn can never get stuck.
 * Every player-written string is untrusted: it is stripped and placed inside <data> blocks.
 */
const fs = require('fs');
const path = require('path');

const LANG_NAMES = { az: 'Azerbaijani', en: 'English' };

function createAnswerProvider({ AS, generate, log }) {
  const file = path.join(__dirname, 'prompts', 'ai_chat_prompt.txt');
  // Re-read when the file changes, but stat it at most once a second (this runs on every AI turn).
  // A failed re-read keeps the last good template.
  let cache = null;
  let checkedAt = -Infinity;
  const template = () => {
    const now = Date.now();
    if (cache && now - checkedAt < 1000) return cache.text;
    checkedAt = now;
    try {
      const m = fs.statSync(file).mtimeMs;
      if (!cache || cache.m !== m) cache = { m, text: fs.readFileSync(file, 'utf8') };
    } catch (e) {
      if (!cache) throw e;
      if (log) log('[ai-chat] keeping previous prompt template: ' + e.message);
    }
    return cache.text;
  };
  const clean = (s) => AS.stripUnsafe(String(s == null ? '' : s)).replace(/[{}]/g, '');

  function buildPrompt(ctx) {
    const level = AS.aiLevel(ctx.level);
    const prev = ctx.previous.length ? ctx.previous.map((a, i) => (i + 1) + '. ' + clean(a.name) + ': ' + clean(a.text)).join('\n') : '(none yet, you answer first)';
    const hist = [];
    if (ctx.own.length) {
      hist.push('YOUR earlier answers (stay consistent with these):');
      for (const e of ctx.own) hist.push('- Q: ' + clean(e.q) + ' | you: ' + clean(e.text));
    }
    if (ctx.pastRounds.length) {
      hist.push("Other players' earlier answers:");
      for (const r of ctx.pastRounds) hist.push('- Q: ' + clean(r.q) + ' | ' + (r.answers.filter((a) => a.name !== ctx.name).map((a) => clean(a.name) + ': ' + clean(a.text)).join(' || ') || '(no answers)'));
    }
    const vars = {
      MY_NAME: clean(ctx.name),
      ALIVE_PLAYERS: ctx.aliveNames.map(clean).join(', '),
      ROUND: ctx.round + ' of ' + ctx.rounds,
      LANGUAGE: LANG_NAMES[ctx.lang] || ctx.lang,
      LEVEL: String(ctx.level),
      STYLE_NOTES: level.styleNotes,
      QUESTION: clean(ctx.question.text),
      PREVIOUS_ANSWERS: prev,
      HISTORY: hist.length ? hist.join('\n') : '(no earlier questions)',
      FACTS: ctx.facts.length ? ctx.facts.map((f) => '- ' + f).join('\n') : '(nothing notable)',
      MAX_CHARS: String(ctx.maxChars),
    };
    // single pass: placeholder-looking text inside untrusted values is never re-expanded
    return template().replace(/\{([A-Z_]+)\}/g, (whole, k) => (k in vars ? vars[k] : whole));
  }

  return {
    async answer(ctx) {
      if (!generate) return null;
      const level = AS.aiLevel(ctx.level);
      const t0 = Date.now();
      const timeoutMs = Math.min(10000, ctx.turnSec * 1000 * 0.45);
      let hard;
      try {
        const prompt = buildPrompt(ctx);
        const raw = await Promise.race([
          generate(prompt, { temperature: level.temperature, maxTokens: level.maxTokens, timeoutMs }),
          new Promise((_, rej) => { hard = setTimeout(() => rej(new Error('timeout')), timeoutMs + 250); }),
        ]);
        return { text: raw, llmMs: Date.now() - t0, source: 'gemini' };
      } catch (e) {
        if (log) log('[ai-chat] ' + ctx.name + ' L' + ctx.level + ' failed: ' + (e && e.message));
        return null;
      } finally { clearTimeout(hard); }
    },
  };
}

module.exports = { createAnswerProvider };
