/* AI IMPOSTOR: SPACE SHIP — Q&A question bank (generated from data/questions.json + game-context questions). */
(function (AS) {
  'use strict';
  // category 'game' = about the match itself (alibis); everything else = human-likeness questions.
  AS.QUESTIONS = [{"id":"daily-01","category":"daily_life","text":{"az":"Bu gün səhər yeməyində nə yedin?","en":"What did you have for breakfast today?"}},
    {"id":"daily-02","category":"daily_life","text":{"az":"Həftə içi adətən saat neçədə yuxudan durursan?","en":"What time do you usually wake up on weekdays?"}},
    {"id":"daily-03","category":"daily_life","text":{"az":"İşə və ya dərsə adətən necə gedirsən?","en":"How do you usually get to work or school?"}},
    {"id":"daily-04","category":"daily_life","text":{"az":"Evə çatan kimi ilk nə edirsən?","en":"What's the first thing you do after getting home?"}},
    {"id":"daily-05","category":"daily_life","text":{"az":"Dünən gecə neçə saat yatdın?","en":"How many hours did you sleep last night?"}},
    {"id":"daily-06","category":"daily_life","text":{"az":"İndi çantanda və ya cibində nə var?","en":"What's in your bag or pocket right now?"}},
    {"id":"daily-07","category":"daily_life","text":{"az":"Səhərlər çay içirsən, yoxsa qəhvə? Necə içirsən?","en":"Coffee or tea in the morning, and how do you take it?"}},
    {"id":"daily-08","category":"daily_life","text":{"az":"Bazar axşamları adətən nə edirsən?","en":"What do you usually do on Sunday evenings?"}},
    {"id":"daily-09","category":"daily_life","text":{"az":"Aldığın son şey nə oldu?","en":"What's the last thing you bought?"}},
    {"id":"daily-10","category":"daily_life","text":{"az":"Nahar fasiləsini adətən necə keçirirsən?","en":"How do you usually spend your lunch break?"}},
    {"id":"daily-11","category":"daily_life","text":{"az":"Telefonunun şarjı indi neçə faizdir?","en":"What's your phone's battery at right now?"}},
    {"id":"daily-12","category":"daily_life","text":{"az":"Bişirməyə üşəndikdə nə yeyirsən?","en":"What's your go-to meal when you're too lazy to cook?"}},
    {"id":"daily-13","category":"daily_life","text":{"az":"Otağını nə qədər tez-tez yığışdırırsan?","en":"How often do you clean your room?"}},
    {"id":"daily-14","category":"daily_life","text":{"az":"Bu gün sənin olduğun yerdə hava necə idi?","en":"What was the weather like where you are today?"}},
    {"id":"daily-15","category":"daily_life","text":{"az":"Səhər ilk açdığın tətbiq hansıdır?","en":"What's the first app you open in the morning?"}},
    {"id":"daily-16","category":"daily_life","text":{"az":"Evdə yemək bişirirsən? Ən yaxşı yeməyin nədir?","en":"Do you cook at home? What's your best dish?"}},
    {"id":"daily-17","category":"daily_life","text":{"az":"Növbədə gözləyəndə adətən nə edirsən?","en":"What do you usually do while waiting in a queue?"}},
    {"id":"opinion-01","category":"opinions","text":{"az":"Pizzaya ananas qoymaq normaldır, yoxsa cinayət?","en":"Is pineapple on pizza okay or a crime?"}},
    {"id":"opinion-02","category":"opinions","text":{"az":"Kim daha məhsuldardır: səhər duranlar, yoxsa gecə quşları?","en":"Who is more productive: early birds or night owls?"}},
    {"id":"opinion-03","category":"opinions","text":{"az":"Mesaja bir neçə saatdan sonra cavab vermək kobudluqdur?","en":"Is it rude to reply to a message hours later?"}},
    {"id":"opinion-04","category":"opinions","text":{"az":"Sosial şəbəkələr xeyir verir, yoxsa zərər?","en":"Does social media do more good or more harm?"}},
    {"id":"opinion-05","category":"opinions","text":{"az":"Hansı daha çox şişirdilir: bazar ertəsi, cümə, yoxsa həftə sonu?","en":"Which is most overrated: Mondays, Fridays or weekends?"}},
    {"id":"opinion-06","category":"opinions","text":{"az":"Dərslər səhər daha gec başlamalıdır?","en":"Should school start later in the morning?"}},
    {"id":"opinion-07","category":"opinions","text":{"az":"Böyük şəhərdə yaşamaq yaxşıdır, yoxsa kiçik şəhərdə?","en":"Is it better to live in a big city or a small town?"}},
    {"id":"opinion-08","category":"opinions","text":{"az":"Filmlər seriallardan yaxşıdır?","en":"Are movies better than TV series?"}},
    {"id":"opinion-09","category":"opinions","text":{"az":"Ən çox şişirdilmiş yemək hansıdır?","en":"What's the most overrated food?"}},
    {"id":"opinion-10","category":"opinions","text":{"az":"Hot-doq sendviçdir?","en":"Is a hot dog a sandwich?"}},
    {"id":"opinion-11","category":"opinions","text":{"az":"İlk baxışdan sevgiyə inanırsan?","en":"Do you believe in love at first sight?"}},
    {"id":"opinion-12","category":"opinions","text":{"az":"Çay pulu məcburi olmalıdır?","en":"Should tipping be mandatory?"}},
    {"id":"opinion-13","category":"opinions","text":{"az":"Ev tapşırığı faydalıdır?","en":"Is homework actually useful?"}},
    {"id":"opinion-14","category":"opinions","text":{"az":"Vaxtında gəlmək yaxşıdır, yoxsa bir az gecikmək?","en":"Is it better to arrive early or a little late?"}},
    {"id":"opinion-15","category":"opinions","text":{"az":"Pişik yoxsa it — hansı daha yaxşı ev heyvanıdır?","en":"Cats or dogs, which make better pets?"}},
    {"id":"opinion-16","category":"opinions","text":{"az":"İctimai yerdə qulaqlıqsız musiqi dinləmək normaldır?","en":"Is it okay to play music without headphones in public?"}},
    {"id":"opinion-17","category":"opinions","text":{"az":"Yay qışdan yaxşıdır?","en":"Is summer better than winter?"}},
    {"id":"pref-01","category":"preferences","text":{"az":"Ən sevdiyin fəsil hansıdır və niyə?","en":"What's your favorite season and why?"}},
    {"id":"pref-02","category":"preferences","text":{"az":"Ən sevdiyin yemək nədir?","en":"What's your favorite food?"}},
    {"id":"pref-03","category":"preferences","text":{"az":"Son vaxtlar hansı musiqiyə qulaq asırsan?","en":"What music have you been into lately?"}},
    {"id":"pref-04","category":"preferences","text":{"az":"Şirin atıştırmalıqlar, yoxsa duzlu?","en":"Sweet snacks or salty snacks?"}},
    {"id":"pref-05","category":"preferences","text":{"az":"Təyyarədə pəncərə kənarı, yoxsa keçid tərəfi?","en":"Window seat or aisle seat?"}},
    {"id":"pref-06","category":"preferences","text":{"az":"Ən sevdiyin rəng hansıdır?","en":"What's your favorite color?"}},
    {"id":"pref-07","category":"preferences","text":{"az":"Dəniz yoxsa dağ?","en":"Sea or mountains?"}},
    {"id":"pref-08","category":"preferences","text":{"az":"Tez yatıb tez duranlardansan, yoxsa gecə quşusan?","en":"Are you an early bird or a night owl?"}},
    {"id":"pref-09","category":"preferences","text":{"az":"İstirahət etmək üçün ən sevdiyin yol hansıdır?","en":"What's your favorite way to relax?"}},
    {"id":"pref-10","category":"preferences","text":{"az":"Ən sevdiyin alkoqolsuz içki hansıdır?","en":"What's your favorite non-alcoholic drink?"}},
    {"id":"pref-11","category":"preferences","text":{"az":"Hansı oyunu ən çox sevirsən?","en":"Which game do you enjoy the most?"}},
    {"id":"pref-12","category":"preferences","text":{"az":"Mesaj yazmağı sevirsən, yoxsa zəng etməyi?","en":"Do you prefer texting or calling?"}},
    {"id":"pref-13","category":"preferences","text":{"az":"Həftənin ən sevdiyin günü hansıdır?","en":"What's your favorite day of the week?"}},
    {"id":"pref-14","category":"preferences","text":{"az":"Kitab oxumağı üstün tutursan, yoxsa video izləməyi?","en":"Do you prefer reading books or watching videos?"}},
    {"id":"pref-15","category":"preferences","text":{"az":"Şəhərində ən sevdiyin yer haradır?","en":"What's your favorite place in your city?"}},
    {"id":"pref-16","category":"preferences","text":{"az":"Hansı janrda filmləri sevirsən?","en":"What kind of movies do you like?"}},
    {"id":"pref-17","category":"preferences","text":{"az":"Pizza, burger, yoxsa kabab — hansını seçərdin?","en":"Pizza, burger or kebab: which one do you pick?"}},
    {"id":"wyr-01","category":"would_you_rather","text":{"az":"Həmişə 10 dəqiqə gec qalmaq, yoxsa həmişə 20 dəqiqə tez gəlmək?","en":"Would you rather always be 10 minutes late or always 20 minutes early?"}},
    {"id":"wyr-02","category":"would_you_rather","text":{"az":"Bir həftə telefonsuz qalmaq, yoxsa pulqabısız?","en":"Would you rather lose your phone or your wallet for a week?"}},
    {"id":"wyr-03","category":"would_you_rather","text":{"az":"Musiqisiz yaşamaq, yoxsa filmsiz?","en":"Would you rather live without music or without movies?"}},
    {"id":"wyr-04","category":"would_you_rather","text":{"az":"Uça bilmək, yoxsa görünməz olmaq?","en":"Would you rather be able to fly or be invisible?"}},
    {"id":"wyr-05","category":"would_you_rather","text":{"az":"Bir ay yalnız pizza, yoxsa yalnız düyü yemək?","en":"Would you rather eat only pizza or only rice for a month?"}},
    {"id":"wyr-06","category":"would_you_rather","text":{"az":"Ev heyvanı kimi əjdaha, yoxsa təkbuynuzlu at?","en":"Would you rather have a pet dragon or a pet unicorn?"}},
    {"id":"wyr-07","category":"would_you_rather","text":{"az":"Bir daha sosial şəbəkədən istifadə etməmək, yoxsa bir daha video izləməmək?","en":"Would you rather never use social media again or never watch videos again?"}},
    {"id":"wyr-08","category":"would_you_rather","text":{"az":"Həyatın üçün geri sarma düyməsi, yoxsa pauza düyməsi?","en":"Would you rather have a rewind button or a pause button for your life?"}},
    {"id":"wyr-09","category":"would_you_rather","text":{"az":"Heyvanlarla danışmaq, yoxsa bütün dilləri bilmək?","en":"Would you rather talk to animals or speak every language?"}},
    {"id":"wyr-10","category":"would_you_rather","text":{"az":"Keçmişdə yaşamaq, yoxsa gələcəkdə?","en":"Would you rather live in the past or in the future?"}},
    {"id":"wyr-11","category":"would_you_rather","text":{"az":"Pulsuz limitsiz yemək, yoxsa pulsuz limitsiz səyahət?","en":"Would you rather have unlimited free food or unlimited free travel?"}},
    {"id":"wyr-12","category":"would_you_rather","text":{"az":"Həmişəlik şirniyyatdan imtina, yoxsa çay-qəhvədən?","en":"Would you rather give up sweets forever or give up coffee and tea forever?"}},
    {"id":"wyr-13","category":"would_you_rather","text":{"az":"Yalnız gecə işləmək, yoxsa yalnız dan yeri sökülərkən?","en":"Would you rather work only at night or only at dawn?"}},
    {"id":"wyr-14","category":"would_you_rather","text":{"az":"Məşhur olmaq, yoxsa varlı amma tanınmamaq?","en":"Would you rather be famous or rich but unknown?"}},
    {"id":"wyr-15","category":"would_you_rather","text":{"az":"Həmişə çox isti, yoxsa həmişə çox soyuq?","en":"Would you rather always be too hot or always too cold?"}},
    {"id":"wyr-16","category":"would_you_rather","text":{"az":"Açarlarını heç vaxt itirməmək, yoxsa telefonunu?","en":"Would you rather never lose your keys or never lose your phone?"}},
    {"id":"wyr-17","category":"would_you_rather","text":{"az":"Hər həftə çox uzun həftə sonu, yoxsa ildə bir dəfə uzun məzuniyyət?","en":"Would you rather have a very long weekend every week or one long vacation a year?"}},
    {"id":"mem-01","category":"memories","text":{"az":"Ən erkən uşaqlıq xatirən nədir?","en":"What's your earliest childhood memory?"}},
    {"id":"mem-02","category":"memories","text":{"az":"Uşaqlıqda ən sevdiyin oyuncaq hansı idi?","en":"What was your favorite toy as a kid?"}},
    {"id":"mem-03","category":"memories","text":{"az":"Həyatında yediyin ən dadlı yemək hansı olub?","en":"What's the best meal you've ever eaten?"}},
    {"id":"mem-04","category":"memories","text":{"az":"Məktəbdəki ilk gününü xatırlayırsan?","en":"Do you remember your first day at school?"}},
    {"id":"mem-05","category":"memories","text":{"az":"Heç vaxt unutmayacağın səyahət hansıdır?","en":"What's a trip you'll never forget?"}},
    {"id":"mem-06","category":"memories","text":{"az":"Ən sevdiyin müəllim kim idi və niyə?","en":"Who was your favorite teacher and why?"}},
    {"id":"mem-07","category":"memories","text":{"az":"Ürəkdən sevdiyin ilk mahnı hansı idi?","en":"What was the first song you really loved?"}},
    {"id":"mem-08","category":"memories","text":{"az":"Məktəbdə başına gələn ən gülməli hadisə nə olub?","en":"What's the funniest thing that happened to you at school?"}},
    {"id":"mem-09","category":"memories","text":{"az":"Uşaqkən kim olmaq istəyirdin?","en":"What did you want to be when you grew up?"}},
    {"id":"mem-10","category":"memories","text":{"az":"Hansı qoxu sənə xatirələri qaytarır?","en":"What smell brings back memories for you?"}},
    {"id":"mem-11","category":"memories","text":{"az":"Ən yaxşı ad günün necə keçib?","en":"Describe your best birthday."}},
    {"id":"mem-12","category":"memories","text":{"az":"İlk telefonun hansı idi?","en":"What was your first phone?"}},
    {"id":"mem-13","category":"memories","text":{"az":"Uşaqkən həyətdə hansı oyunu oynayırdın?","en":"What game did you play outside as a kid?"}},
    {"id":"mem-14","category":"memories","text":{"az":"Nənən və ya babanla bağlı bir xatirən danış.","en":"Share a memory with your grandparents."}},
    {"id":"mem-15","category":"memories","text":{"az":"Axırıncı dəfə nə vaxt gözlərindən yaş gələnə qədər güldün?","en":"When did you last laugh until you cried?"}},
    {"id":"mem-16","category":"memories","text":{"az":"Pul yığıb aldığın ilk şey nə idi?","en":"What was the first thing you ever saved money for?"}},
    {"id":"mem-17","category":"memories","text":{"az":"Uşaqlığından darıxdığın yer haradır?","en":"What place from your childhood do you miss?"}},
    {"id":"humor-01","category":"light_humor","text":{"az":"Super qəhrəman adın nə olardı?","en":"What would your superhero name be?"}},
    {"id":"humor-02","category":"light_humor","text":{"az":"Həyatın film olsaydı, adı nə olardı?","en":"If your life were a movie, what would it be called?"}},
    {"id":"humor-03","category":"light_humor","text":{"az":"Gizlicə sevdiyin ən qəribə yemək kombinasiyası nədir?","en":"What's the weirdest food combo you secretly love?"}},
    {"id":"humor-04","category":"light_humor","text":{"az":"Bir günlük pişik olsan, nə edərdin?","en":"What would you do if you woke up as a cat for a day?"}},
    {"id":"humor-05","category":"light_humor","text":{"az":"Ən faydasız istedadın nədir?","en":"What's your most useless talent?"}},
    {"id":"humor-06","category":"light_humor","text":{"az":"Hansı heyvanla dava etsən uduzardın?","en":"Which animal do you think you'd lose a fight against?"}},
    {"id":"humor-07","category":"light_humor","text":{"az":"Nədənsə yayınmaq üçün işlətdiyin ən pis bəhanə hansı olub?","en":"What's the worst excuse you've used to get out of something?"}},
    {"id":"humor-08","category":"light_humor","text":{"az":"Zombi apokalipsisində peşən nə olardı?","en":"What would your job be in a zombie apocalypse?"}},
    {"id":"humor-09","category":"light_humor","text":{"az":"Gördüyün ən gülməli avtomatik düzəliş səhvi hansı olub?","en":"What's the funniest autocorrect fail you've seen?"}},
    {"id":"humor-10","category":"light_humor","text":{"az":"Akvarium balığına nə ad qoyardın?","en":"What would you name a pet goldfish?"}},
    {"id":"humor-11","category":"light_humor","text":{"az":"Tərəvəz olsaydın, hansı olardın?","en":"If you had to be a vegetable, which one would you be?"}},
    {"id":"humor-12","category":"light_humor","text":{"az":"Ən mənasız qorxun nədir?","en":"What's the silliest thing you're afraid of?"}},
    {"id":"humor-13","category":"light_humor","text":{"az":"Məşhur rəqs hərəkətin hansıdır?","en":"What's your signature dance move?"}},
    {"id":"humor-14","category":"light_humor","text":{"az":"Ən pis super gücün nə olardı?","en":"What would be the worst superpower?"}},
    {"id":"humor-15","category":"light_humor","text":{"az":"Otağa girəndə hansı mahnı çalmalıdır?","en":"What song should play when you enter a room?"}},
    {"id":"humor-16","category":"light_humor","text":{"az":"Son vaxtlar axtardığın ən qəribə şey nə olub?","en":"What's the weirdest thing you've searched for recently?"}},
    {"id":"humor-17","category":"light_humor","text":{"az":"Səni ən çox əsəbiləşdirən mənasız şey nədir?","en":"What's your most irrational pet peeve?"}},
    {"id":"game-where-body","category":"game","text":{"az":"Cəsəd tapılanda sən harada idin?","en":"Where were you when the body was found?"}},
    {"id":"game-last-task","category":"game","text":{"az":"Sonuncu hansı tapşırığı etdin?","en":"Which task did you finish last?"}},
    {"id":"game-last-seen","category":"game","text":{"az":"Gördüyün son adam kim idi?","en":"Who was the last person you saw?"}},
    {"id":"game-most-time","category":"game","text":{"az":"Ən çox vaxtı hansı otaqda keçirdin?","en":"Which room did you spend the most time in?"}},
    {"id":"game-strange","category":"game","text":{"az":"Qəribə bir şey gördün? Nə?","en":"Did you notice anything strange? What?"}},
    {"id":"game-trust","category":"game","text":{"az":"İndi kimə ən çox güvənirsən və niyə?","en":"Who do you trust the most right now, and why?"}},
    {"id":"game-before-meeting","category":"game","text":{"az":"Yığıncaqdan əvvəl hansı otaqdan keçdin?","en":"Which room did you walk through just before the meeting?"}},
    {"id":"game-last-minute","category":"game","text":{"az":"Son bir dəqiqədə nə ilə məşğul idin?","en":"What were you doing in the last minute?"}},
    {"id":"game-suspicious","category":"game","text":{"az":"Bu gün sənə kim daha şübhəli göründü?","en":"Who looked the most suspicious to you today?"}},
    {"id":"game-followed","category":"game","text":{"az":"Kimsə səni izləyirdi?","en":"Did anyone follow you around?"}},
    {"id":"game-task-count","category":"game","text":{"az":"İndiyə qədər neçə tapşırıq bitirmisən?","en":"How many tasks have you finished so far?"}},
    {"id":"game-vents","category":"game","text":{"az":"Kimisə ventilyasiyadan çıxan gördün?","en":"Did you see anyone use the vents?"}},
    {"id":"game-nearest","category":"game","text":{"az":"Sənə ən yaxın olan adam kim idi?","en":"Who was closest to you a moment ago?"}},
    {"id":"game-start-with","category":"game","text":{"az":"Raundun əvvəlində yanında kim vardı?","en":"Who was with you at the start of the round?"}},
    {"id":"game-ship-system","category":"game","text":{"az":"Gəminin hansı sistemi indi ən çox diqqət tələb edir?","en":"Which ship system needs the most attention right now?"}},
    {"id":"game-who-alone","category":"game","text":{"az":"Tək qalan biri oldu? Kim?","en":"Was anyone walking around alone? Who?"}}];
})(globalThis.AS = globalThis.AS || {});
